name: Deploy to ECS

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  BACKEND_ECR_REPO: mindguard-backend
  FRONTEND_ECR_REPO: mindguard-frontend
  BACKEND_ECS_SERVICE: mindguard-backend-service
  FRONTEND_ECS_SERVICE: mindguard-frontend-service
  ECS_CLUSTER: mindguard-cluster

jobs:
  deploy-backend:
    name: Backend → ECS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push backend image
        id: build-backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$BACKEND_ECR_REPO:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/$BACKEND_ECR_REPO:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$BACKEND_ECR_REPO:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download backend task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition mindguard-backend \
            --query taskDefinition > backend-task-def.json

      - name: Update backend task definition image
        id: backend-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: backend-task-def.json
          container-name: mindguard-backend
          image: ${{ steps.build-backend.outputs.image }}

      - name: Deploy backend to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.backend-task-def.outputs.task-definition }}
          service: ${{ env.BACKEND_ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

  deploy-frontend:
    name: Frontend → ECS
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push frontend image
        id: build-frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            -t $ECR_REGISTRY/$FRONTEND_ECR_REPO:$IMAGE_TAG ./frontend
          docker push $ECR_REGISTRY/$FRONTEND_ECR_REPO:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$FRONTEND_ECR_REPO:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download frontend task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition mindguard-frontend \
            --query taskDefinition > frontend-task-def.json

      - name: Update frontend task definition image
        id: frontend-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: frontend-task-def.json
          container-name: mindguard-frontend
          image: ${{ steps.build-frontend.outputs.image }}

      - name: Deploy frontend to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.frontend-task-def.outputs.task-definition }}
          service: ${{ env.FRONTEND_ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
